name: GitBook Continuous Integration

on:
  workflow_run:
    workflows: ["README Continuous Integration"]
    types:
      - completed

jobs:
  GitBook-CI:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare SUMMARY.md
        run: echo -e "# Table of contents\\n\\n* [Summary](README.md)"> ./SUMMARY.md

      - name: Install pandoc
        run: docker pull pandoc/core

      - name: Convert to html
        run: |
          LN="${{ github.event.repository.name }} Lecture Notes"
          EN="${{ github.event.repository.name }} Exam Notes"
          if test -f "./$LN.tex"; then
            pandoc --mathjax -s "./$LN.tex" -o "./$LN.html"
            echo "* [Lecture Notes]($LN.html)" >> SUMMARY.md
          fi
          if test -f "./$EN.tex"; then
            pandoc --mathjax -s "./$EN.tex" -o "./$EN.html"
            echo "* [Exam Notes]($EN.html)" >> SUMMARY.md
          fi

      - name: Push files to repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit -m "GitBook CI"
          git push
